# action.yml
name: "Action for Mina Deploy"
description: "Deploy Ruby 3.3.0 usign mina"
branding:
  icon: "arrow-right-circle"
  color: "red"
inputs:
  ssh_private_key: # id of input
    description: "Private key that can access servers"
    required: true
    default: "---empty---"
  command: # id of input
    description: "Command to run on mina deployer"
    required: true
    default: "deploy"
  environment: # id of input
    description: "Environment where command as to be runned"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.environment }}
    - ${{ inputs.command }}
